[package]
org = "ballerinax"
name = "health.dicom"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "DICOM", "PACS"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.dicom"
export = ["health.dicom"]

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
path = "../native/build/libs/dicom-native-0.1.0.jar"
